---
- name: APT - set sources
  template:
    src: "{{ item.src }}.j2"
    dest: "/etc/apt/{{ item.dest }}"
  loop:
    - {'src': 'sources.list', 'dest': 'sources.list'}
    - {'src': 'backports.list', 'dest': 'sources.list.d/backports.list'}
  register: apt_debian_sources

- name: APT - update debian sources
  apt: update_cache=yes
  when: apt_debian_sources.changed

- name: APT - install essential packages
  apt:
    name: "{{ essential_packages }}"

- name: Snapd - install packages
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  loop: "{{ snap_packages }}"
  ignore_errors: yes

- name: Create default directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  loop: "{{ directories }}"

# Compton
- name: Configure Compton
  template:
    src: compton.conf.j2
    dest: "{{ user_config_path }}/compton/compton.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart compton

# Suckless Terminal
# TODO package should be downloaded and extracted and built
# File should be exists in this role.
- name: Check if suckless terminal (st) is installed 
  stat:
    path: /usr/local/bin/st
  register: st_installed

- name: Extract suckless terminal (st)
  unarchive:
    src: st-0.8.2.tar.gz
    dest: "{{ user_config_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  when: not st_installed.stat.exists

- name: Configure suckless terminal (st)
  template:
    src: st_config.h.j2
    dest: "{{ user_config_path }}/st-0.8.2/config.h"
    owner: "{{ user }}"
    group: "{{ group }}"
  register: st_configured

- name: Build Suckless terminal (st)
  command: make clean install
  args: 
    chdir: "{{ user_config_path }}/st-0.8.2/"
  when: st_configured.changed

# Xmonad
- name: Configure xmonad
  template:
    src: xmonad.hs.j2
    dest: "{{ xmonad_config_path }}/xmonad.hs"
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart xmonad

# Xmobar
- name: Configure xmobars
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_config_path }}/xmobar/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  loop:
    - xmobarrc0
    - xmobarrc1
  notify: restart xmonad

# .Xresources
- name: Configure .Xresources
  template: 
    src: .Xresources.j2
    dest: "{{ user_home_path }}/.Xresources"
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: reload xresources

# Fonts
- name: Install Fonts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/share/fonts/{{ item | basename }}"
    owner: root
    group: root
  loop: "{{ q('fileglob', 'files/fonts/*.ttf') }}"
  notify: update font cache
  
# Nitrogen & wallpapers
- name: Copy wallpapers
  synchronize:
    src: wallpapers/
    dest: "{{ user_wallpaper_path }}"

- name: Configure nitrogen & wallpaper
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_config_path }}/nitrogen/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  loop: 
    - nitrogen.cfg
    - bg-saved.cfg
  register: nitrogen_status
  notify: restore nitrogen
  
# Lock Screen (i3lock)
- name: Configure i3lock script
  template:
    src: lock_multi_screen.sh.j2
    dest: "{{ user_config_path }}/i3lock/lock_multi_screen.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
  
# Language
- name: Create change language script
  template:
    src: change-lang.sh.j2
    dest: "{{ user_config_path }}/change-lang.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: a+x
  notify:
    - restart xmonad

# Bash Aliases
- name: Enable bash aliases
  template: 
    src: .bash_aliases.j2
    dest: "{{ user_home_path }}/.bash_aliases"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644

- name: Configure polkit policies
  template:
    src: "{{ item }}.j2"
    dest: "/etc/polkit-1/localauthority/50-local.d/{{ item }}"
  loop:
    - allow-mount-policy.pkla
  notify: restart polkit

# sysctl
# Used by reactjs watcher
- name: Configure sysctl
  template: 
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: Add default user to virt-manager group
  user:
    name: "{{ user }}"
    group: libvirt
    append: yes
    